{% set name = "rayoptics" %}
{% set version = "0.6.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b9fc209e08359e4952ac307cdeec581e04a4616a0611a76ba2bee158b0d77ea1

build:
  number: 0
  noarch: python
  entry_points:
    - rayoptics = rayoptics.qtgui.rayopticsapp:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pyscaffold >=3.1a0,<3.2a0
    - python >=3.7
  run:
    - attrs >=19.1.0
    - ipywidgets >=7.5.1
    - json_tricks >=3.13.2
    - matplotlib-base >=3.1.1
    - numpy >=1.17.1
    - opticalglass >=0.7.0
    - pandas >=0.25.1
    - pyqt <5.13
    - python >=3.7
    - qdarkstyle >=2.8
    - qtconsole >=4.5.5
    - ipython >=7.19
    - requests >=2.23.0
    - scipy >=1.3.1
    - traitlets >=4.3.2
    - transforms3d >=0.3.1

test:
  imports:
    - rayoptics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/rayoptics/
  summary: Tools for image forming optical design and analysis
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    rayoptics is a Python geometrical optics and image forming optics library.
    It provides a geometric ray tracing foundation for the analysis of image
    forming and coherent optical systems. A number of standard geometrical
    analysis options such as transverse ray and wavefront aberration analysis
    are provided on this base. Paraxial layout of optical systems is also
    supported by y-ybar diagrams and graphical editing of paraxial rays in
    lens layout views. Import of Zemax .zmx and CODEV .seq files is supported.
    RayOptics can be used in Python scripts, the Python and IPython shells,
    the Jupyter notebook, and a Qt-based graphical user interface application.
  doc_url: https://rayoptics.readthedocs.io/
  dev_url: https://github.com/mjhoptics/rayoptics

extra:
  recipe-maintainers:
    - mjhoptics
