{% set name = "rayoptics" %}
{% set version = "0.8.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f56d6d8d635931f4cbfe6cb36752d686fd6955d7dced62beec04ce8528acf799

build:
  number: 3
  noarch: python
  entry_points:
    - rayoptics = rayoptics.qtgui.rayopticsapp:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pyscaffold >=4.3
    - python >=3.8
  run:
    - python >=3.8
    - opticalglass >=1.0.3
    - numpy >=1.21.5
    - scipy >=1.7.3
    - matplotlib-base >=3.5.1
    - pandas >=1.3.5
    - anytree >=2.8.0
    - transforms3d >=0.3.1
    - requests >=2.27.1
    - packaging >=21.3
    - json_tricks >=3.15.5
    - deprecation >=2.1.0
    - ipywidgets >=7.6.5
    - pyqt <5.16
    - qdarkstyle >=3.0.2, <3.1.0
    - qtconsole >=5.3.0, <5.4.0
    - ipython >=7.31.0
    - traitlets >=5.1.1

test:
  imports:
    - rayoptics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/rayoptics/
  summary: Tools for image forming optical design and analysis
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    rayoptics is a Python geometrical optics and image forming optics library.
    It provides a geometric ray tracing foundation for the analysis of image
    forming and coherent optical systems. A number of standard geometrical
    analysis options such as transverse ray and wavefront aberration analysis
    are provided on this base. Paraxial layout of optical systems is also
    supported by y-ybar diagrams and graphical editing of paraxial rays in
    lens layout views. Import of Zemax .zmx and CODEV .seq files is supported.
    RayOptics can be used in Python scripts, the Python and IPython shells,
    the Jupyter notebook, and a Qt-based graphical user interface application.
  doc_url: https://rayoptics.readthedocs.io/
  dev_url: https://github.com/mjhoptics/rayoptics

extra:
  recipe-maintainers:
    - mjhoptics
